import type { routing } from '@/i18n/routing';
import type messages from './messages/en.json';

/**
 * next-intl 4.0.0
 *
 * https://github.com/amannn/next-intl/blob/main/examples/example-app-router/global.d.ts
 */
declare module 'next-intl' {
  interface AppConfig {
    Locale: (typeof routing.locales)[number];
    Messages: typeof messages;
  }
}

/**
 * Static image asset module declarations.
 *
 * Next.js normally injects these via `next-env.d.ts`, which is autogenerated by
 * `next dev` / `next build` and gitignored. Our CI typecheck job runs `tsc
 * --noEmit` without first running Next.js, so `next-env.d.ts` never exists in
 * CI and asset imports like `import Banner from '@/public/images/docs/banner.png'`
 * blow up with TS2307.
 *
 * Declaring the asset modules here makes the type graph CI-independent — local
 * dev, Vercel build, and the GitHub Actions typecheck all see the same types
 * without depending on a generated file.
 */
declare module '*.png' {
  const content: import('next/image').StaticImageData;
  export default content;
}
declare module '*.jpg' {
  const content: import('next/image').StaticImageData;
  export default content;
}
declare module '*.jpeg' {
  const content: import('next/image').StaticImageData;
  export default content;
}
declare module '*.webp' {
  const content: import('next/image').StaticImageData;
  export default content;
}
declare module '*.avif' {
  const content: import('next/image').StaticImageData;
  export default content;
}
declare module '*.gif' {
  const content: import('next/image').StaticImageData;
  export default content;
}
declare module '*.svg' {
  const content: import('next/image').StaticImageData;
  export default content;
}
